:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

= Constituents mapping options

This page covers options for handling data from the TMS Constituents table and its related tables, including: ConAddress, ConAltNames, ConDates, ConEMail, ConPhones, ConTypes

See also:

* xref:names.adoc[General name options]

toc::[]

== General (across constituent-related tables)

These are set in https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/constituents.rb[the Constituents config].

=== Preferred name field for persons

See https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/choosing_preferred_name_form_for_persons.adoc[Choosing preferred form of name for Person authorities].

Setting name:: `:preferred_name_field`
Default option:: `:alphasort` (inverted form)

There is also a `:var_name_field` (i.e. non-preferred name field) setting. This is set to `:displayname` if `:alphasort` is the preferred name form. The values are swapped if inverted form of name is preferred.

=== Include non-preferred name form as variant name?

Setting name:: `:include_flipped_as_variant`
Default option:: `false` (we do not create a variant name in the authority for the non-preferred name form)
Alternate option(s):: `true` (we create a variant name in the authority for the non-preferred name form)

For help in understanding the implications, see https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/authority_main_variant_term_functionality.adoc[Authority main and variant term functionality].

[TIP]
====
In your staging instance, enter some person names with only your preferred name form in the authority record. Then, test out whether this will work for you in terms of:

* data entry (try using these person names in some test records)
* search
====


== Constituents table

These are set in https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/constituents.rb[the Constituents config].

=== `:map_approved`

`approved` is a Boolean (yes/no) field in TMS. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- it is unclear if the functionality of this field in TMS maps to anything supported in CS. This field is dropped

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Suggested implementation would be:

If `approved` = 1/yes/true for a name, the term status value *_in the first/primary term field group of the CS authority record_* is set to "accepted". If `approved` = 0/no/false for a name, no term status value is provided in the CS authority.

=== `:map_active`

`active` is a Boolean (yes/no) field in TMS. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- There is no real CS functionality supporting active vs. inactive authorities. This data is dropped.

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Some alternate implementations for this field could include:

* If `active` = 1/yes/true for a name, we add a Group value of "active constituents" to the CS authority record. If `active` = 0/no/false for a name, we add a Group value of "inactive constituents" to the CS authority record.
* Only migrate names where `active` = 1/yes/true. NOTE: this can cause data loss if inactive constituent names are used in objects, accessions, and other places in the database.

=== `:map_isstaff`

`isstaff` is a Boolean (yes/no) field in TMS. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- There is no CS functionality supporting staff vs. nonstaff authorities, so this data is dropped.

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Some alternate implementations for this field could include:

* If `isstaff` = 1/yes/true for a name migrating as a Person authority, we add a Term type value of "Employee" to the CS authority record. If `isstaff` = 1/yes/true for a name migrating as an Organization authority, we do nothing. If `isstaff` = 0/no/false for a name, we do nothing.
* If `isstaff` = 1/yes/true for a name, we add a Group value of "staff" to the CS authority record. If `isstaff` = 0/no/false for a name, we do nothing.

=== `:map_isprivate`

`isstaff` is a Boolean (yes/no) field in TMS. The TMS data dictionary indicates this field is used to indicate whether a constituent is a private collector. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- There is no CS functionality supporting authorities representing private collectors vs other names.

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Some alternate implementations for this field could include:

* If `isprivate` = 1/yes/true for a name, we add a Group value of "private collectors" to the CS authority record. If `isprivate` = 0/no/false for a name, we do nothing.

=== Append date data to names?
If there is date data for a name, this can be appended to the actual name value.

Default option:: `:duplicates` - during processing, we check for duplicate name values. Date values, when present, are appended to duplicate name values in hopes of disambiguating the duplicates automatically using existing data.

.Alternate option(s)
`:none`:: no dates will be appended to names. Any duplicate disambiguation will be done by client in TMS and/or cleanup worksheets
`:all`:: date values, when present, will be appended to all names
`:person`:: date values, when present, will be appended to all person names
`:organization`:: date values, when present, will be appended to all organization names


== ConAddress table
=== Non-configurable processing details

* If multiple addresses are associated with a single name, the TMS `ConAddress.rank` field is used to order the addresses in CS.

=== Configurable processing details
Please see https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/con_address.rb[our default settings for migrating ConAddress data]. Apologies for making you look at (sort of) code, but there are plain text descriptions of each setting and what it does.

Your migration specialist will let you know if any of these defaults have been overridden.

Let your migration specialist know if you want to change any of the settings.




=== Reports that may be provided for review

con_address_countries_clean_review.csv:: Addresses with country values that cannot be exactly or cleanly mapped to CS countries vocabulary. Will require custom `ConAddress.config.country_remappings` settings.
con_address_dropping.csv:: Addresses dropped from migration because (1) they are for constituents that are not migrating; (2) they are marked inactive and the migration is set to omit inactive addresses; or (3) there was no address data in the row
con_address_duplicates.csv:: Addresses dropped from migration because, once data was processed/shaped, the address duplicated another address for the same constituent. **Remarks/notes for the address were NOT included in deduplication process, so this report is given in case any important info was dropped from those fields.**
constituents_with_multiple_address.csv:: Address data for names that will have more than one address merged in the migration. Clients may want to review and clean these up post migration.
