:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

= Constituents mapping options

This page covers options for handling data from the TMS Constituents table and its related tables, including: ConAddress, ConAltNames, ConDates, ConEMail, ConPhones, ConTypes

See also:

* xref:names.adoc[General name options]

toc::[]

== General (across constituent-related tables)

These are set in https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/constituents.rb[the Constituents config].

=== Preferred name field for persons

See https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/choosing_preferred_name_form_for_persons.adoc[Choosing preferred form of name for Person authorities].

Setting name:: `:preferred_name_field`
Default option:: `:alphasort` (inverted form)

There is also a `:var_name_field` (i.e. non-preferred name field) setting. This is set to `:displayname` if `:alphasort` is the preferred name form. The values are swapped if inverted form of name is preferred.

=== Include non-preferred name form as variant name?

Setting name:: `:include_flipped_as_variant`
Default option:: `false` (we do not create a variant name in the authority for the non-preferred name form)
Alternate option(s):: `true` (we create a variant name in the authority for the non-preferred name form)

For help in understanding the implications, see https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/authority_main_variant_term_functionality.adoc[Authority main and variant term functionality].

[TIP]
====
In your staging instance, enter some person names with only your preferred name form in the authority record. Then, test out whether this will work for you in terms of:

* data entry (try using these person names in some test records)
* search
====


== Constituents table

These are set in https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/constituents.rb[the Constituents config].

=== `:map_approved`

`approved` is a Boolean (yes/no) field in TMS. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- it is unclear if the functionality of this field in TMS maps to anything supported in CS. This field is dropped

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Suggested implementation would be:

If `approved` = 1/yes/true for a name, the term status value *_in the first/primary term field group of the CS authority record_* is set to "accepted". If `approved` = 0/no/false for a name, no term status value is provided in the CS authority.

=== `:map_active`

`active` is a Boolean (yes/no) field in TMS. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- There is no real CS functionality supporting active vs. inactive authorities. This data is dropped.

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Some alternate implementations for this field could include:

* If `active` = 1/yes/true for a name, we add a Group value of "active constituents" to the CS authority record. If `active` = 0/no/false for a name, we add a Group value of "inactive constituents" to the CS authority record.
* Only migrate names where `active` = 1/yes/true. NOTE: this can cause data loss if inactive constituent names are used in objects, accessions, and other places in the database.

=== `:map_isstaff`

`isstaff` is a Boolean (yes/no) field in TMS. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- There is no CS functionality supporting staff vs. nonstaff authorities, so this data is dropped.

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Some alternate implementations for this field could include:

* If `isstaff` = 1/yes/true for a name migrating as a Person authority, we add a Term type value of "Employee" to the CS authority record. If `isstaff` = 1/yes/true for a name migrating as an Organization authority, we do nothing. If `isstaff` = 0/no/false for a name, we do nothing.
* If `isstaff` = 1/yes/true for a name, we add a Group value of "staff" to the CS authority record. If `isstaff` = 0/no/false for a name, we do nothing.

=== `:map_isprivate`

`isstaff` is a Boolean (yes/no) field in TMS. The TMS data dictionary indicates this field is used to indicate whether a constituent is a private collector. This setting controls whether this field is mapped into CS in the migration.

Default option:: `false` -- There is no CS functionality supporting authorities representing private collectors vs other names.

.Alternate option(s)
`true`:: Field value will be mapped into CS. Exact mapping/handling will need to be implemented.

Some alternate implementations for this field could include:

* If `isprivate` = 1/yes/true for a name, we add a Group value of "private collectors" to the CS authority record. If `isprivate` = 0/no/false for a name, we do nothing.

=== Append date data to names?
If there is date data for a name, this can be appended to the actual name value.

Default option:: `:duplicates` - during processing, we check for duplicate name values. Date values, when present, are appended to duplicate name values in hopes of disambiguating the duplicates automatically using existing data.

.Alternate option(s)
`:none`:: no dates will be appended to names. Any duplicate disambiguation will be done by client in TMS and/or cleanup worksheets
`:all`:: date values, when present, will be appended to all names
`:person`:: date values, when present, will be appended to all person names
`:organization`:: date values, when present, will be appended to all organization names


== ConAddress table
=== Non-configurable processing details

* If multiple addresses are associated with a single name, the TMS `ConAddress.rank` field is used to order the addresses in CS.

=== Configurable processing details
Please see https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/con_address.rb[our default settings for migrating ConAddress data]. Apologies for making you look at (sort of) code, but there are plain text descriptions of each setting and what it does.

Your migration specialist will let you know if any of these defaults have been overridden.

Let your migration specialist know if you want to change any of the settings.

=== Reports that may be provided for review

con_address_countries_clean_review.csv:: Addresses with country values that cannot be exactly or cleanly mapped to CS countries vocabulary. Will require custom `ConAddress.config.country_remappings` settings.
con_address_dropping.csv:: Addresses dropped from migration because (1) they are for constituents that are not migrating; (2) they are marked inactive and the migration is set to omit inactive addresses; or (3) there was no address data in the row
con_address_duplicates.csv:: Addresses dropped from migration because, once data was processed/shaped, the address duplicated another address for the same constituent. **Remarks/notes for the address were NOT included in deduplication process, so this report is given in case any important info was dropped from those fields.**
constituents_with_multiple_address.csv:: Address data for names that will have more than one address merged in the migration. Clients may want to review and clean these up post migration.

== `ThesXrefs` merge treatments

The TMS `ThesXrefs` table stores terms/values of different types for merge into various target tables, including `Constituents`.

Your Migration Specialist will let you know about any custom cleanup and preparation of these values prior to merging them into `Consituents`. Usually this involves some handling of any `:remarks` values that may have been recorded for individual xrefs.

Each `:thesxreftype` must be assigned a treatment, which is used to merge the term values into the `Constituents` data as shaped for CollectionSpace. Multiple values are merged into a single Constituent record in order of the `:displayorder` value for `ThesXrefs` row. The available treatments are:

=== drop

Rows with this treatment assigned to their `:thesxreftype` will be omitted from the migration.

=== birth_founding_place

*Initial processing*

The `:termpreferred` value from rows with this treatment will be mapped to `Constituents` `:term_birth_founding_place_preferred`. The `:termused` value is mapped to `Constituents` `:term_birth_founding_place_used`. The `:remarks` value is mapped to `Constituents` `:term_birth_founding_place_note`.

NOTE: Any birth_founding_place info that may have been merged in from `ConGeography` will take precedence over such data merged in from `ThesXrefs` in subsequent processing.

*TECHNICAL NOTE:* `:term_birth_founding_place_preferred`, `:term_birth_founding_place_used`, and `:term_birth_founding_place_note` must be merged in like a repeatable field group for subsequent processing to be possible.

*Person processing*

.If `Person` `birthPlace` field is authority controlled
* The first `:term_birth_founding_place_preferred` value will be mapped to `birthPlace` field. If there is a `:term_birth_founding_place_note` value associated with first value, it is mapped to `:term_note_birthplace` with prefix [.value]#Birth place field value note:#.
* If there are more than one `:term_birth_founding_place_used` values, the first (represented by the preferred term mapped to `birthPlace`) is discarded. Subsequent values are concatenated into a note string with prefix label: [.value]#Subsequent birth place(s):#, which is mapped to `:term_note_birthplace` field

.If `Person` `birthPlace` field is free text
* The first `:term_birth_founding_place_used` value will be mapped to `birthPlace` field. If there is an associated `:term_birth_founding_place_note` value, it will be appended to the `birthPlace` field, separated by " -- ".
* If there are more than one `:term_birth_founding_place_used` values, subsequent values are concatenated into a note string with prefix label: [.value]#Subsequent birth place(s):#, which is mapped to `:term_note_birthplace` field.

.Regardless of `birthPlace` authority controlled/free text status
* If any birthPlace info was merged in from `ConGeography`, the first value from that data will be mapped to `birthPlace`, and all `:term_birth_founding_place_used` values prepared and mapped as a note string as described above.
* Any `:term_note_birthplace` values are mapped to `bioNote` field.

*Organization processing*

This is handled the same as for Person, but with mappings to `foundingPlace`, and `historyNote` fields, with note labels reflecting founding place.

=== death_dissolution_place

*Initial processing*
This is handled the same  as `birth_founding_place`, but "death_dissolution" in the target `Constituent` fields instead of "birth_founding".

*Organization processing*

Organization records do not have a `dissolutionPlace` field, so any `:term_death_dissolution_place_used` values are concatenated into a string separated by "; ". The whole string is prepended with label [.value]#Dissolution place(s):# and mapped to `historyNote` field.

Any `:term_death_dissolution_place_note` values are concatenated into a string separated by "; ". The whole string is prepended with label [.value]#Dissolution place note(s):# and mapped to `historyNote` field.

*Person processing*

Logic is the same as for `birth_founding_place`, but mapping into `deathPlace` field, and tweaking note field labels to say "death" instead of "birth".

=== gender

*Initial processing*

The `:termpreferred` value from rows with this treatment will be mapped to `Constituents` `:term_gender`. The `:remarks` value is mapped to `Constituents` `:term_gender_note`. The `:thesxreftype` value is mapped to `Consitutents` `:term_gender_label`.

*TECHNICAL NOTE:* `:term_gender`, `:term_gender_note`, and `:term_gender_label` must be merged in like a repeatable field group for subsequent processing to be possible.

*Person processing*

.If there is one `:term_gender` value for the person
* `:term_gender` value is mapped to `Person` `gender` field
* If there is a `:term_gender_note` value, it is transformed as per the pattern `{term_gender_label} note on Gender field value: {term_gender_note}`, and mapped to the `:term_note_gender` field

.If there is more than one `:term_gender` value for the same person
* Term, note, and label values are split into "preceding" and "final" groups for processing. The "preceding" group can have any number of values.
* All "preceding" values are mapped to the `:term_note_gender` field, transformed as per the pattern `{term_gender_label} note: {term_gender} -- {term_gender_note}`
* Final `:term_gender` value mapped to the `Person` `gender` field.
* Final `:term_gender_note` value, if any, is transformed as per the pattern `{term_gender_label} note on Gender field value: {term_gender_note}`, and mapped to the `:term_note_gender` field

`:term_note_gender` value will be mapped to the `Person` `bioNote` field.

*Organization processing*

All values will be treated as "preceding" values are in persons with more than one `term_gender` value.

`:term_note_gender` values will be mapped to `Organization` `historyNote` field.

If any such values are present, your Migration Specialist will likely flag them for post-migration review, since Organizations are not expected to have gender.

=== nationality

*Initial processing*

The `:termused` value from rows with this treatment will be mapped to `Constituents` `:term_nationality`. The `:remarks` value is mapped to `Constituents` `:term_nationality_note`. The `:thesxreftype` value is mapped to `Consitutents` `:term_nationality_label`.

NOTE: Any nationality info that may have been merged in from `ConGeography` will take precedence over such data merged in from `ThesXrefs` in subsequent processing.

*TECHNICAL NOTE:* `:term_nationality`, `:term_nationality__note`, and `:term_nationality_label` must be merged in like a repeatable field group for subsequent processing to be possible.

*Person processing*

.If there is no `Person` `nationality` value from other data sources
* The first `:term_nationality_used` and `:term_nationality_note` values will be concatenated (with " -- " as separator) and mapped to `nationality` field.
* If there are more than one `:term_nationality_used` values, subsequent values are combined and mapped to `bioNote` following the pattern:

`{term_nationality_label value} note: {term_nationality_used} -- {term_nationality_note}`

.If there is a `Person` `nationality` value from another data source
* All values are combined following the pattern described above and mapped to `bioNote`.

*Organization processing*

All values are combined following the pattern described above and mapped to `historyNote`.

=== plain_note

*Initial processing*

The following pattern is mapped into `Constituents` `:term_plain_note` field:

`Untyped note: {termused value} -- {remarks value}`

*Person processing*

`:term_plain_note` is mapped into `nameNote`.

*Organization processing*

`:term_plain_note` is mapped into `historyNote`.

=== type_labeled_internal_note_*

*Initial processing*

The `*` is a free value that will be treated as part of the intermediate field group name, to ensure all values of the same category will appear together in a logical group in the target note field.

The field name pattern is: `term_internal_note_{* value}`.

You may have 7 different `:thesxreftype` values assigned type_labeled_internal_note_copyright treatment, and 3 assigned type_labeled_internal_note_contact treatment.

Each `ThesXrefs` row will produce a separate note string, formatted like:

`{thesxreftype value}: {termused value} -- {remarks value}`

The exception is when the `:termused` value is "see remarks" or something equivalent. In this case, the pattern used is:

`{thesxreftype value}: {remarks value}`

Your Migration Specialist will list any `:termused` values that trigger the second pattern.

NOTE: Currently all fields in CollectionSpace authority term records are private---only viewable by your staff in the CollectionSpace web application. The public/private distinction here is just in the type of information expected to be recorded in the target fields. For instance, if we ever added Person/Organization authority publishing to the CollectionSpace public browser, we would likely include `bioNote` in the public display, but not `nameNote`.

*Person processing*

These notes will be mapped to `nameNote`.

*Organization processing*

Organization does not currently have an internal facing note field, so these must be mapped to `historyNote`.


=== type_labeled_public_note_*

*Initial processing*

Same as for type_labeled_internal_note_* treatment.

*Person processing*

Values map to `bioNote`

*Organization processing*

Values map to `historyNote`.
