:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

= Constituents mapping options

toc::[]

== Preferred name field for persons

See https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/choosing_preferred_name_form_for_persons.adoc[Choosing preferred form of name for Person authorities].

Default option:: `:displayname` (direct form)

== Include non-preferred name form as variant name?

Default option:: `false` (we do not create a variant name in the authority for the non-preferred name form)
Alternate option(s):: `true` (we create a variant name in the authority for the non-preferred name form)

For help in understanding the implications, see https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/authority_main_variant_term_functionality.adoc[Authority main and variant term functionality].

[TIP]
====
In your staging instance, enter some person names with only your preferred name form in the authority record. Then, test out whether this will work for you in terms of:

* data entry (try using these person names in some test records)
* search
====

== Uncategorized authority default

This is mainly relevant if you are skipping the name review/cleanup process. If you are going through that process, you are probably assigning appropriate category (Person or Organization) to each name.

If any are left uncategorized, or if you are skipping that process altogether, we have to what authority to create those names in for the migration.

Default option:: Person
Alternate option(s):: Organization

== `approved` field handling

This is a Boolean (yes/no) field in TMS

Default option:: `:nomigrate` -- it is unclear if the functionality of this field in TMS maps to anything supported in CS. This field is dropped

.Alternate option(s)
`:termstatus`:: If `approved` = 1/yes/true for a name, the term status value *_in the first/primary term field group of the CS authority record_* is set to "accepted". If `approved` = 0/no/false for a name, no term status value is provided in the CS authority.

== `active` field handling

Default option:: `:nomigrate` -- There is no CS functionality supporting active vs. inactive authorities.

.Alternate option(s)
`:group`:: If `active` = 1/yes/true for a name, we add a Group value of "active constituents" to the CS authority record. If `active` = 0/no/false for a name, we add a Group value of "inactive constituents" to the CS authority record.
`:drop`:: Only migrate names where `active` = 1/yes/true. NOTE: this can cause data loss if inactive constituent names are used in objects, accessions, and other places in the database. 

== `isstaff` field handling

Default option:: `:nomigrate` -- There is no CS functionality supporting staff vs. nonstaff authorities.

.Alternate option(s)
`:termtype`:: If `isstaff` = 1/yes/true for a name migrating as a Person authority, we add a Term type value of "Employee" to the CS authority record. If `isstaff` = 1/yes/true for a name migrating as an Organization authority, we do nothing. If `isstaff` = 0/no/false for a name, we do nothing.
`:group`:: If `isstaff` = 1/yes/true for a name, we add a Group value of "staff" to the CS authority record. If `isstaff` = 0/no/false for a name, we do nothing.

== `isprivate` field handling

The TMS data dictionary indicates this field is used to indicate whether a constituent is a private collector.

Default option:: `:nomigrate` -- There is no CS functionality supporting authorities representing private collectors vs other names.

.Alternate option(s)
`:group`:: If `isprivate` = 1/yes/true for a name, we add a Group value of "private collectors" to the CS authority record. If `isprivate` = 0/no/false for a name, we do nothing.

== Append date data to names?
If there is date data for a name, this can be appended to the actual name value.

Default option:: `:duplicates` - during processing, we check for duplicate name values. Date values, when present, are appended to duplicate name values in hopes of disambiguating the duplicates automatically using existing data.

.Alternate option(s)
`:none`:: no dates will be appended to names. Any duplicate disambiguation will be done by client in TMS and/or cleanup worksheets
`:all`:: date values, when present, will be appended to all names
`:person`:: date values, when present, will be appended to all person names
`:organization`:: date values, when present, will be appended to all organization names

