:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

= Names mapping options

This page covers broad options for handling name data from TMS. They apply to any names, not just those from a given TMS table.

These options are set in https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/names.rb[the Names config]. That file may contain other config that is less important to explain to clients.

See also:

* xref:constituents.adoc[Options for names derived from Constituents table]

toc::[]

== Uncategorized authority default

This is mainly relevant if you are skipping the name review/cleanup process. If you are going through that process, you are probably assigning appropriate category (Person or Organization) to each name.

If any are left uncategorized, or if you are skipping that process altogether, we have to what authority to create those names in for the migration.

Setting name:: `:untyped_default`
Default option:: Person
Alternate option(s):: Organization
