:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

=  Mapping settings for ObjAccession, AccessionLot, and RegistrationSets tables

toc::[]

== TMS data structure overview and migration treatment categories

There is one row per object in the system in the ObjAccession table. However, there seems to be a lot of flexibility in how users can enter this data, which calls for different approaches, or _treatments_ for the different patterns of data in the migration process.

The treatments we have identified are detailed below.

[IMPORTANT]
====
It is assumed that, if a `:linkedset`, `:linkedlot` or `:lotnumber` approach has been taken, then all accessions info for objects included in those sets or lots is the same. That is, object-specific accession data is not entered for any of the objects.

This assumption is based on our understanding of the intended function of AccessionLot and RegistrationSets, derived from analysis of multiple clients' TMS data, and the limited information available in the TMS Data Dictionary.

The migration will use the accession details from the first encountered row in the set/lot.

We can run checks to identify any ObjAccession rows associated with AccessionLot and RegistrationSets that have extra/different info from the rest of the objects in the lot or set. This information can be provided to the client, who can determine how to handle the information in CS post-migration. We are unable to handle it in migration as it is unexpected and the data pattern is not well-supported by the CS data model.
====


=== `:linkedset`
Registration sets containing one or more objects can be linked to an accession lot, which results in population of:

* AccessionLot and RegistrationSets tables
* `acquisitionlotid` and `registrationsetid` fields in ObjAccession table

One CS Acquisition procedure is created per Registration Set. All objects in ObjAccession table related to a given Registration Set are related to the Acquisition procedure.

This treatment has two sub-treatment categories:

`:singleset`:: If there is one Registration Set associated with an Accession Lot, the resulting Acquisition procedure's reference number is the :lotnumber value from the AccessionLot table.

`:multiset`:: If there are multiple Registration Sets per Accession Lot, the resulting Acquisition procedure's reference number begins with the :lotnumber value from the AccessionLot table. Some additional value must be added to ensure reference number uniqueness. If present, the AccessionLot.lotpattern field value will be used as a pattern to derive this. Otherwise a sequential digit segment may be added.

=== `:linkedlot`
This treatment is applied if one or more objects are linked to an accession lot without being assigned to a registration set, in a way that results in:

* population of AccessionLot table but not RegistrationSets table
* population of `acquisitionlotid` field, but not `registrationsetid` field, in ObjAccession table


NOTE: It is unknown if this ever occurs. I have not seen it in actual client data, but it looks as though it may be supported

One CS Acquisition procedure is created per accession lot. The `AccessionLot.LotNumber` value becomes the CS `acquisitionreferencenumber` value.

Relationships are created between the procedure and the linked objects from the ObjAccession table.

=== `:lotnumber`

Due to patterns seen in client data, we gather that TMS allows population of the `acquisitionlot` field in the ObjAccession table _without_ linking that object to an entry in the AccessionLot table.

From reviewing multiple TMS data sets from different clients, it looks like all the acquisition details in objects given the same `acquisitionlot` value are the same for all objects.

One CS Acquisition procedure is created per unique `acquisitionlot` value in the ObjAccession table. The `acquisitionlot` value becomes the CS `acquisitionreferencenumber`.

All objects in ObjAccession table with the given `acquisitionlot` value are related to the Acquisition procedure.

NOTE: Any `acquisitionnumber` values in rows with this treatment are collected, deduplicated, and written to a note field in the acquisition procedure, where they will be indexed for keyword search or an advanced search on that note field. See (<<acq_number_treatment,:acq_number_treatment>>).

=== `:acqnumber`

This treatment applies to rows where ObjAccession `registrationsetid`, `acquisitionlotid`, and `acquisitionlot` fields are empty and the `acquisitionnumber` field is populated.

We have worked with client data where the same `acquisitionnumber` has been applied to many rows in the ObjAccession table, but different information has been entered for each object. A simplified example is shown below:

....
| acquisitionnumber | objectnumber | acquisitionsource | acquisitionmethod |
|               123 |        123.1 | Someone           | gift              |
|               123 |        123.2 | Someone else      | purchase          |
|               123 |        123.3 | Someone           | gift              |
|               123 |        123.4 | Someone else      | purchase          |
....

Therefore, this treatment does the following:

* Groups/clumps the records for each `acquisitionnumber` on unique data in all non-id fields in the record
* Creates one Acquisition procedure per group. Adds an incrementing numeral value to the `acquisitionnumber` value to create unique `acquisitionreferencenumber` values in CS.

With the above data, we would get two Acquisitions procedures, numbered 123.001 and 123.002.

Objects 123.1 and 123.3 would be related to Acquisition 123.001.

Objects 123.2 and 123.4 would be related to Acquisition 123.002.

NOTE: It is not currently possible to turn off the addition of the incrementing suffix if there is only one group of objects.


=== `:onetoone`

This applies to rows where the ObjAccession `registrationsetid`, `acquisitionlotid`, `acquisitionlot`, and `acquisitionnumber` fields are empty.

==== settings: `row_treatment`
There are three treatment options for these rows, set in the `OneToOneAcq.row_treatment` setting.

*The default treatment is `:grouped`.*

The acquisition reference number deriver transformer is set in the `OneToOneAcq.acq_ref_num_deriver` setting. The default acquisition reference number deriver drops the final segment following a `.` in the given object number. Given object number, `2022.23.18`, it will return `2022.23`. Given object number `TMS1008`, it will return `TMS1008`. If necessary, your Migration Specialist will develop a custom acquisition reference number deriver transformer for your data.

Here is sample base data to compare the three possible :onetoone treatments:

....
| objectnumber | acquisitionsource | acquisitionmethod | acquisitiondate | creditline         |
|--------------+-------------------+-------------------+-----------------+--------------------|
|        123.1 | Someone           | gift              |      2015-12-19 | Gift of the artist |
|        123.2 | Someone else      | purchase          |      2020-01-23 | Funds from donor   |
|        123.3 | Someone           | gift              |      2015-12-19 | Gift of the artist |
|        383.1 | Someone else      | purchase          |      2020-01-23 | Funds from donor   |
|        383.2 | Someone           | gift              |      2015-12-19 | Gift of the artist |
|        383.3 | Someone           | gift              |      2015-12-19 | Gift of the artist |
|       99.2.1 | Someone           | gift              |      2015-12-19 | Gift of the artist |
|       99.2.2 | Someone else      | purchase          |      2020-01-23 | Funds from donor   |
|       87.5.1 | Someone           | gift              |      2015-12-19 | Gift of the artist |
|       87.5.2 | Someone           | gift              |      2015-12-19 | Gift of the artist |
....

===== `:separate`

One CS Acquisition procedure is created per ObjAccession row. The relevant object is related to the Acquisition procedure. The resulting Acquisition procedure's reference number is the related object's object number.

Given the above sample data:

* 10 Acquisition records will be created in CollectionSpace. The `:objectnumber` values are used as the `:acquisitionreferencenumber`
* Each Acquisition record will be linked to the object with its matching objectnumber

===== `:grouped`

The values of all fields except `:objectid` are concatenated (with fieldname labels for each value) into one `:combined` field. One CS Acquisition procedure is created per unique `:combined` value.

The Acquisition reference number value is derived from the object number of the first object assigned to the acquistion procedure. The Acquisition reference number deriver will be customized to your data. A three digit incrementing number is added to the end of the derived acquisition number to ensure uniqueness.

All objects represented by rows with that `:combined` value will be linked to the Acquisition procedure.

This option creates fewer Acquisition procedures, with more objects linked to each acquisition, than does the `:onetoone_grouped_with_id` option.

Given the above sample data, 2 Acquisition records will be created:

* Acquisition reference number: 123 grp 001
** *Acquisition data:* source: Someone, acquisition method: gift, date: 2015-12-19, creditline: Gift of the artist
** Linked to objects: 123.1, 123.3, 383.2, 383.3, 99.2.1, 87.5.1, 87.5.2
* Acquisition reference number: 123 grp 002
** *Acquisition data:* source: Someone else, acquisition method: purchase, date: 2020-01-23, creditline: Funds from donor
** Linked to objects: 123.2, 383.1, 99.2.2

===== `:grouped_with_id`

An Acquisition reference number value is derived from each row's object number. The Acquisition reference number deriver will be customized to your data.

The values of all fields, including the derived acquisition reference number, are concatenated (with fieldname labels for each value) into one `:combined` field. One CS Acquisition procedure is created per unique `:combined` value. A three digit incrementing number is added to the end of the derived acquisition number to ensure uniqueness.

All objects represented by rows with that `:combined` value will be linked to the Acquisition procedure.

This option creates more Acquisition procedures, with fewer objects linked to each acquisition, than does the `:onetoone_grouped` option.

Given the above sample data, 2 Acquisition records will be created:

* Acquisition reference number: 123 grp 001
** *Acquisition data:* source: Someone, acquisition method: gift, date: 2015-12-19, creditline: Gift of the artist
** Linked to objects: 123.1, 123.3
* Acquisition reference number: 123 grp 002
** *Acquisition data:* source: Someone else, acquisition method: purchase, date: 2020-01-23, creditline: Funds from donor
** Linked to objects: 123.2
* Acquisition reference number: 383 grp 001
** *Acquisition data:* source: Someone else, acquisition method: purchase, date: 2020-01-23, creditline: Funds from donor
** Linked to objects: 383.1
* Acquisition reference number: 383 grp 002
** *Acquisition data:* source: Someone, acquisition method: gift, date: 2015-12-19, creditline: Gift of the artist
** Linked to objects: 383.2, 383.3
* Acquisition reference number: 99.2 grp 001
** *Acquisition data:* source: Someone, acquisition method: gift, date: 2015-12-19, creditline: Gift of the artist
** Linked to objects: 99.2.1
* Acquisition reference number: 99.2 grp 002
** *Acquisition data:* source: Someone else, acquisition method: purchase, date: 2020-01-23, creditline: Funds from donor
** Linked to objects: 99.2.2
* Acquisition reference number: 87.5
** *Acquisition data:* source: Someone, acquisition method: gift, date: 2015-12-19, creditline: Gift of the artist
** Linked to objects: 87.5.1, 87.5.2

==== settings: `group_id_uniquifier_separator`

String added between derived acquisition reference number for a group and auto-incrementing digits added to ensure unique reference numbers across acquisition records derived from :onetoone treatment with :grouped or :grouped_with_id row treatment.

Defaults to: " grp "

Considerations: Separated from preceding and subsequent segments by spaces to support keyword searching on "grp". Omitting the spaces, or using punctuation instead, would result in "grp" not being its own separately searchable keyword.

== Ensuring unique CollectionSpace Acquisition reference numbers

Each of the above treatments happens in its own processing silo. This means that we can end up with an Acquisition from a :linkedlot treatment with reference number "87.5", _and_ an an Acquisition from :onetoone treatment with the same reference number value.

This is a problem for ingesting and batch managing Acquisitions in CollectionSpace, so we check for this and use another incremental digit sequence to ensure unique reference number values as needed. Here, we would end up with final reference numbers:

* 87.5 uniq 001
* 87.5 uniq 002

==== settings: `id_uniquifier_separator`

String added between acquisition reference number and auto-incrementing digits added to ensure unique reference numbers across CollectionSpace acquisition records.

Defaults to: " uniq "

Considerations: Separated from preceding and subsequent segments by spaces to support keyword searching on "uniq". Omitting the spaces, or using punctuation instead, would result in "uniq" not being its own separately searchable keyword.

== Dates in TMS ObjAccessions vs CS Acquisition

As you can see from the table below, there are only two TMS ObjAccessions date fields that have an unambiguous one-to-one mapping to the CS acquisition procedure.

How to handle the other date values, if they appear in a client's data, is controlled by the <<mapping-options,mapping options>> described below.

NOTE: Some "No longer in use" TMS fields are included because we sometimes find client data in these fields.

[cols="1,2,1,2", options="header"]
|===
|TMS field
|TMS data dictionary def
|CS field
|https://collectionspace.atlassian.net/wiki/spaces/COL/pages/506953729/Configuration+and+Data+Maps+-+Cataloging+Procedures+and+Vocabularies[CS schema] def

|accessionisodate
|Date of Accessioning (ISO date format)
|accessiondate
|The date on which an object formally enters the collection and is recorded in the accessions register.

|accessionminutes1
|No longer in use.  Replaced by ApprovalISODate1
|
|

|accessionminutes2
|No longer in use.  Replaced by ApprovalISODate2
|
|

|
|
|acquisitiondate
|The date on which title to an object or group of objects is transferred to the organization.

|approvalisodate1
|Approval Date 1 (ISO date format)
|
|

|approvalisodate2
|Approval Date 2 (ISO date format)
|
|

|authdate
|Date that an acquisition was authorized
|acquisitionauthorizerdate
|The date of which the Acquisition authorizer gives final approval for an acquisition to proceed.

|deedofgiftreceivediso
|Date Deed of Gift was received
|
|

|deedofgiftsentiso
|Date Deed of Gift was sent
|
|

|initdate
|Date that an acquisition was first initiated
|
|

|suggestedvalueisodate
|Value Date for the Suggested Accession Value in the linked Accession Lot
|
|
|===


== Mapping settings

[NOTE]
====
The RegistrationSets and AccessionLot tables contain fields that also appear in ObjAccession. The field handling specified for such fields in ObjAccession cascades to RegistrationSets and AccessionLot.

That is, you cannot opt to have :accessionvalue information treated differently for rows being processed as Registration Sets vs. one-to-one acquisition/object relations.
====

.Support for approval field group
[NOTE]
====
[[approval-field-group-profiles]]Many of the mapping options below will refer to whether the profile support the approval field group. As of CollectionSpace version 7.2 (September 2023), this field group is present in the following community supported domain profiles:

* core
* anthro
* bonsai
* fcart
* lhmc
* publicart

The following profiles do _not_ have the approval field group: botgarden, herbarium, materials.
====

=== :accessionvalue_treatment

Applies to values in `ObjAccession.accessionvalue` or `AccessionLot.accessionvalue` fields

NOTE: recording values in ObjAccession.accessionvalue is apparently no longer supported in newer versions of TMS, replaced by linking to an ObjectValue record. However, we still see it in client data.

If `:valuation_control` option is used, this also causes `valuationnotes` field value to be mapped to a valuation control procedure.

Default option:: `:valuation_control`

Other options to be developed on client request.

==== :accessionvalue_treatment = :valuation_control details
Preprocessing for ObjAccession table/:onetoone treatment rows:

* First we merge in the values of any linked ObjInsurance records
* If the value of :accessionvalue field = the value in the linked ObjInsurance record, we delete it from ObjAccession (because we are going to create the relevant Valuation Control (VC) procedure from the ObjInsurance record)
* If the value of :accessionvalue field is different from the value in the linked ObjInsurance record, or if there is no linked ObjInsurance record, the value is retained for further processing.

No preprocessing for AccessionLot.accessionvalue/:linkedlot treatment rows.

One CS Valuation Control (VC) procedure is created to reflect the recorded value. The VC procedure is linked to the relevant CS acquisition procedure and objects.

.Related options
* `:accessionvalue_type` - :valuetype to enter in VC procedures derived from this data. Default: "Original Value"

=== :acq_number_treatment

This applies only:

* to rows handled with `:lotnumber` treatment
* where there is a separate `acquisitionnumber` value

TIP: This is configured in the TMS::LotNumAcq config module.

The value of the setting is the name of the CS note field the `acquisitionnumber`(s) should be mapped to.

Default option:: `:acquisitionnote` -- map into this note field

.Alternate options
* `:acquisitionprovisos`
* `:acquisitionreason`
* `:drop` - do not migrate this information

.Related settings
* `:acq_number_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Acquisition number value(s): "

=== :auth_date_source_pref

NOTE: This setting is only applied if the client's CollectionSpace domain profile does not include the approval field group in the Acquisition record. If the approval field group is not available, we want to get some relevant date value from TMS into an actual date-formatted field in CollectionSpace. If the approval field group is available, all relevant dates will be recorded in date-formatted fields in CollectionSpace, so we don't need to do this manipulation.

Due to differing data entry practices in TMS and the <<dates-in-tms-objaccessions-vs-cs-acquisition,data model differences in the date table above>> we need to build in flexibility for the source of data mapped to CS `acquisitionauthorizerdate` field.

Default option:: `%i[authdate approvalisodate1 approvalisodate2]`

With the default option:

* if there is a value in `authdate`, it is mapped to `acquisitionauthorizerdate`
* if `authdate` is empty and there is a value in `approvalisodate1`, that value is mapped to `acquisitionauthorizerdate`
* if `authdate` and `approvalisodate1` are empty, and there is a value in `approvalisodate2`, that value is mapped to `acquisitionauthorizerdate`

NOTE: If an approval date field value is mapped to `acquisitionauthorizerdate`, the source field is no longer available for further processing, and thus will not be repeated because of <<approval_date_treatment>> settings.

=== :approval_date_treatment
Applies to `:approvalisodate1` and `:approvalisodate2` fields in ObjAccession table.

The TMS `:authdate` field is mapped to CS `:acquisitionauthorizerdate` field, but that is a single-valued field.

This option specifies what to do with approval date data.

Default option if profile includes approval group fields:: `:approvalgroup` -- map each date value into an instance of [.csfield]#approvalDate# field
Default option if profile does not include approval group fields:: `:acquisitionnote` -- map into [.csfield]#acquisitionNote# field

.Alternate options
* `:acquisitionprovisos`-- map into [.csfield]#acquisitionProvisos# field
* `:drop` - do not migrate this information

==== Related settings if using `:approvalgroup` option

===== `:approvalisodate1_status`

Value used in [.csfield]#approvalStatus# field in approval group row in which date is recorded. This value is added as a controlled term in the "Approval Status" vocabulary

Default option:: "approved"

.Alternate option(s)
* Any string requested by client

===== `:approvalisodate2_status`

Value used in [.csfield]#approvalStatus# field in approval group row in which date is recorded. This value is added as a controlled term in the "Approval Status" vocabulary

Default option:: "approved (subsequent)"

.Alternate option(s)
* Any string requested by client

==== Related settings if using `:acquisitionnote` or `:acquisitionprovisos` options

===== `:approval_date_note_format`

If treatment involves mapping the value(s) to a note, should it be one combined note or two separate note values.

Default option:: `:combined`.

.Alternate option(s)
* `:separate` - This option is useful if data entry practice means these two date fields have been used to record dates with different meanings that should be labeled differently

===== `:approval_date_note_combined_prefix`

If treatment involves mapping the value to a note, and `:approval_date_note_format` is `:combined`, this is the string prepended to the combined value to clarify the meaning of the value.

Default option:: "Approval date(s): "

.Alternate option(s)
* Any string requested by client

===== `:approval_date_note_1_prefix`

If treatment involves mapping the value to a note, and `:approval_date_note_format` is `:separate`, this is the string prepended to the value to clarify the meaning of the value of `:approvalisodate1`.

Default option:: "Initial approval date: "

.Alternate option(s)
* Any string requested by client

===== `:approval_date_note_2_prefix`

If treatment involves mapping the value to a note, and `:approval_date_note_format` is `:separate`, this is the string prepended to the value to clarify the meaning of the value of `:approvalisodate2`.

Default option:: "Subsequent approval date: "

.Alternate option(s)
* Any string requested by client

=== :authorizer_org_treatment
Applies to :authorizer field in ObjAccession table *_if name in field has been categorized by client as an Organization name_*

The TMS `:authorizer` field is mapped to CS [.csfield]#acquisitionAuthorizer# field if it is a Person name, but Organization names cannot be used to populate this field.

The option specifies what to do with Organization names in TMS `:authorizer`.

Default option if profile includes approval group fields:: `:approvalgroup` -- map organization name into an instance of [.csfield]#approvalGroup# field. The organization name will become a controlled vocabulary term in the Approval Group vocabulary. The [.csfield]#approvalStatus# for the row will be set to `authorized`. The `:authdate` value (if populated) will be copied to the [.csfield]#approvalDate# field in the row
Default option if profile does not include approval group fields:: `:acquisitionnote` -- map into [.csfield]#acquisitionNote# field

.Alternate options:
* `:acquisitionprovisos`-- map into [.csfield]#acquisitionProvisos# field
* `:acquisitionreason` -- map into [.csfield]#acquisitionReason# field
* `:drop` - do not migrate this information


==== Related settings if using `:acquisitionnote` , `:acquisitionprovisos`, or `:acquisitionReason` options

===== `:authorizer_org_prefix`

If treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value.

Default option:: "Authorized by (organization name): "

.Alternate options:
* Any string requested by client

=== :authorizer_note_treatment
Applies to :authorizer field in ObjAccession table *_if name in field has been categorized by client as treated as a note_*

The option specifies what to do with note values in TMS `:authorizer`.

Default option if profile includes approval group fields:: `:approvalgroup` -- map value into an instance of [.csfield]#approvalGroup# field. The value will become a controlled vocabulary term in the Approval Group vocabulary. The [.csfield]#approvalStatus# for the row will be set to `authorized`. The `:authdate` value (if populated) will be copied to the [.csfield]#approvalDate# field in the row
Default option if profile does not include approval group fields:: `:acquisitionnote` -- map into [.csfield]#acquisitionNote# field

.Alternate options:
* `:acquisitionprovisos`-- map into this note field
* `:acquisitionreason` -- map into this note field
* `:drop` - do not migrate this information

==== Related settings if using `:acquisitionnote` , `:acquisitionprovisos`, or `:acquisitionReason` options

===== `:authorizer_note_prefix`

If treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value.

Default option:: "Authorizer note: "

.Alternate options:
* Any string requested by client

=== :dog_dates_treatment
Applies to `:deedofgiftsentiso` and `:deedofgiftreceivediso` fields in ObjAccession and RegistrationSets tables.

CS does not have structured data fields specifically to record this info. The option specifies how data in these fields will be used.

note field this data should be mapped into.

"Deed of gift sent: " will be prepended to any :deedofgiftsentiso field values.

"Deed of gift received: " will be prepended to any :deedofgiftreceivediso field values.

Default option if profile includes approval group fields:: `:approvalgroup` -- map each value into an instance of [.csfield]#approvalDate# field. The [.csfield]#approvalStatus# for the row will be set to `deed of gift sent` or `deed of gift received`.
Default option if profile does not include approval group fields:: `:acquisitionnote` -- map into [.csfield]#acquisitionNote# field

.Alternate options:
* `:acquisitionprovisos`
* `:drop` - do not migrate this information

=== :initiation_treatment
Applies to the :initiator and :initdate fields in the ObjAccession table.

CS does not have structured data fields specifically to record this info. The option specifies how `:initiator` and `:initdate` field values will be handled.


That string is mapped into the field indicated by this option:

Default option if profile includes approval group fields:: `:approvalgroup` -- if `:initiator` value is mapped to a Person name, map value into an instance of [.csfield]#approvalIndividual# field. If it was mapped to Organization or Note, it will be mapped to [.csfield]#approvalGroup# and the value will become a controlled vocabulary term in the Approval Group vocabulary. The [.csfield]#approvalStatus# for the row will be set to `initiated`. The `:initdate` value (if populated) will be mapped to the [.csfield]#approvalDate# field in the row
Default option if profile does not include approval group fields:: `:acquisitionreason` -- map into [.csfield]#acquisitionReason# field

.Alternate options:
* `:acquisitionnote`
* `:acquisitionprovisos`
* `:drop` - do not migrate this information

==== Related settings if using `:acquisitionnote` , `:acquisitionprovisos`, or `:acquisitionReason` options

===== `:initiation_prefix`

If treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value.

Default option:: "Initiated: "

.Alternate options:
* Any string requested by client

===== Note generation

https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/transforms/obj_accession/initiation_note.rb[`Tms::Transforms::ObjAccession::InitiationNote` ] generates a string with the following pattern:

`{initiation_prefix} {initiator}, {initdate}`

=== :loaned_object_treatment
TMS creates an ObjAccession row for every Object entered, whether it is a loaned object or you ever intend to enter acquisitions-related data for it.

This setting controls how to handle data in the ObjAccession (and related tables) for Objects that are linked to Loans In.

Default option:: `:creditline_to_loanin` -- unique Object `creditline` values for all objects linked to a given Loan In are gathered, and mapped into the Loan In record's Credit Line field. Rows for these objects are removed from ObjAccession before transforming that data into CS Acquisition procedures.

.Alternate options:
* `:drop` - ObjAccession rows for objects linked to Loans In are removed from the ObjAccession table before we start creating CS Acquisition procedures
* `:as_acquisitions` - Rows for objects linked to Loans In will be treated like any other ObjAccession rows. If other settings result in an Acquisition procedure being created for such objects, they will be related to both an Acquisition record and a Loan In record in CS.

=== Mapping names into :acquisitionsource vs. :owner

[IMPORTANT]
.CS definitions of "owner" and "acquisitionsource" fields
====
The following are taken from the Acquisition:Common schema https://collectionspace.atlassian.net/wiki/spaces/COL/pages/506953729/Configuration+and+Data+Maps+-+Cataloging+Procedures+and+Vocabularies[available on the CS wiki].

owner:: Details of a People, Person or Organisation who owned an object before title was transferred to the organization
acquisitionsource:: The People, Person, or Organization from whom an object was obtained, if different from the owner. The Acquisition source may be an agent or other intermediary between the acquiring organization and the Owner. For archaeological archives, use Acquisition source to record the excavating body responsible for preparing and depositing the archive with the organization.

We use these definitions to guide our initial/suggested mappings when developing custom migrations, but clients are not required to follow these. We can customize the role mappings into these fields to make them work for the client.
====

TMS Constituent names are merged into other TMS tables via the `ConRefs` and `ConRefDetails` tables, which indicate the following for each name to be merged in:

* constituent ID
* target table
* target record id (in target table)
* role id (looks up role values like "Donor" or "Vendor")
* role type id (looks up role type values like "Object Related" or "Acquisition Related")

The https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/role_types.rb[migration application's RoleTypes configuration] maps all TMS role types to the TMS tables into which Constituent names should be merged. These mappings can be overridden per client on request, but by default names tagged with "Acquisiton Related" role type will be merged into TMS ObjAccessions table, which then gets transformed/mapped into CS Acquisition procedures.

Each client will have used different role values on their Acquisition Related constituent references, so a per-client configuration mapping each role value to the appropriate CS field is set up.

.Example per-client constituent role treatment mapping for ObjAccession
[source,ruby]
----
  Kiba::Tms::ObjAccession.config.con_ref_role_to_field_mapping = {
    :owner => ["Associated Source", "Attributed Source", "Donor", "Lender",
               "Source"],
    :acquisitionsource => ["Vendor"]
  }
----

We do an initial mapping based on the definitions in the info box above, but these can be changed on client request.

[NOTE]
====
Due to differences in data model granularity between TMS (more granular in this case) and CS, the role values for names mapped to `:owner` and `:acquisitionsource` are, by default, lost in migration.

If you view the Acquisition procedure form in your CS instance, you will see there is no structured place to put this information.

If it is crucial for you to retain the TMS role information in the CS Acquisition procedure, we can develop a mapping of owner/acquisitionsource name + role value into one of the notes fields. Thus far, no TMS client has requested this
====

=== :note_sources
Controls what TMS fields will get concatenated together and mapped to CS `acquisitionnote` note field.

Default value(s):: `%i[source remarks]`

Configuring other settings described on this page can add fields to the list.

=== :percentowned_treatment

Applies to ObjAccession.currpercentownership and RegistrationSets.percentowned fields.

CS does not have structured data fields to reflect this information. The option specifies which note field this data should be mapped into.

Default option:: `:acquisitionprovisos`

.Alternate options:
* `:acquisitionnote`
* `:drop` - do not migrate this information

.Related settings
* `:percentowned_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Percent owned: "

Other options may be developed on client request, if feasible.

=== :proviso_sources
Controls what TMS fields will get concatenated together and mapped to CS `acquisitionprovisos` note field.

Default value(s):: `%i[acquisitionterms]`

Configuring other settings described on this page can add fields to the list.

=== :reason_sources
Controls what TMS fields will get concatenated together and mapped to CS `acquisitionreason` note field.

Default value(s):: `%i[acqjustification]`

Configuring other settings described on this page can add fields to the list.

=== :valuationnote_treatment

This applies to the `valuationnotes` field if

* there is no `accessionvalue` value, OR
* `:accessionvalue_treatment` is set to something other than `:valuation_control`

Default option:: `:acquisitionnote`

.Alternate options:
* `:acquisitionprovisos`
* `:drop` - do not migrate this information

.Related settings
* `:valuationnote_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Valuation note: "

Other options may be developed on client request, if feasible.

=== `TextEntries` merge treatments

The TMS `TextEntries` table stores text values of different types for merge into various target tables, including ``ObjAccession`.

Your Migration Specialist will let you know about any custom cleanup and preparation of these values prior to merging them into `ObjAccession`. Usually this involves some handling of any `:purpose` and `:remarks` values that may have been recorded for individual text entries. Typically we combine these values into the `:textentry` field so that we have one main content field to merge.

Constituent names associated with text entries will have been merged in as `:org_author` and `:person_author` fields prior to merge into `ObjAccession`.

Each `:texttype` must be assigned a treatment, which is used to merge the text entry into the `ObjAccession` data as shaped for CollectionSpace. The available treatments are:

==== drop

Text entries with this treatment assigned to their `:texttype` will be omitted from the migration.

==== acq_note

[[text_entry_acq_note]]Text entries with this treatment assigned to their `:texttype` will be merged into [.csfield]#acquisitionNote#.

The text entry data is transformed into a note value following this pattern:

Capitalized `:texttype`: `:textentry` --`:person_author`, `:org_author`, `:textdate`

Multiple values in the target field are separated by 2 carriage returns.

==== approval_group

IMPORTANT: This treatment can only be used if <<approval-field-group-profiles,your domain profile supports the approval field group in the CollectionSpace Acquisition record>>.

Text entries with this treatment assigned to their `:texttype` will be merged into the CollectionSpace Acquisition  approval fields with the following mappings:

* `:texttype` ➡️ [.csfield]#approvalStatus#
* `:textentry` ➡️ [.csfield]#approvalNote#
* `:textdate` ➡️ [.csfield]#approvalDate#
* `:person_author` ➡️ [.csfield]#approvalIndividual#
* `:org_author` ➡️ [.csfield]#approvalGroup#

Values mapped to the [.csfield]#approvalGroup# field will be added to the Approval Group term list.

==== proviso_note

Text entries with this treatment assigned to their `:texttype` will be merged into [.csfield]#acquisitionProvisos#.

The <<text_entry_acq_note,acq_note note pattern described above>> is used for this note as well.

Multiple values in the target field are separated by 2 carriage returns.

==== reason_note

Text entries with this treatment assigned to their `:texttype` will be merged into [.csfield]#acquisitionReason#.

The <<text_entry_acq_note,acq_note note pattern described above>> is used for this note as well.

Multiple values in the target field are separated by 2 carriage returns.
