:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

=  Mapping options for ObjAccession, AccessionLot, and RegistrationSets tables

toc::[]

== TMS data structure overview and migration treatment categories

There is one row per object in the system in the ObjAccession table.

Depending on client TMS data entry practice there may or may not be any data in AccessionLot and/or RegistrationSets tables.

These tables can be used to describe the accession of multiple objects as a group accession. One or more objects can be associated with a Registration Set. One or more registration sets can be associated with an Accession Lot. If this structure is used, it appears that the AccessionLot and RegistrationSets tables become populated in TMS, and IDs linking objects to the appropriate records are added to the ObjAccession table. This is referred to in the migration as `:linkedlot` treatment.

It also appears that objects can be associated with an Accession Lot without creation of any RegistrationSets. Or, at least, there is some way of entering data that causes the AccessionLot and RegistationSets tables to be blank, but there is a lot number value in the `:acquisitionlot` field of ObjAccession, and all rows having the same lot number have the same other accession information. This is referred to as `:lotnumber` treatment in the migration.

ObjAccession rows with no links to AccessionLot/RegistrationSets tables or values in :acquisitionlot field are treated as `:onetoone` in the migration.

[CAUTION]
====
It is assumed that, if a `:linkedset`, `:linkedlot` or `:acquisitionlot` approach has been taken, then all accessions info for objects included in those sets or lots is the same. That is, object-specific accession data is not entered for any of the objects.

This assumption is based on our understanding of the intended function of AccessionLot and RegistrationSets, derived from analysis of multiple clients' TMS data, and the limited information available in the TMS Data Dictionary.

We can run checks to identify any ObjAccession rows associated with AccessionLot and RegistrationSets that have extra/different info from the rest of the objects in the lot or set. This information can be provided to the client, who can determine how to handle the information in CS post-migration. We are unable to handle it in migration as it is unexpected and not well-supported by the CS data model.
====

The treatment categories are treated as follows in the migration:


=== `:linkedset`

One CS Acquisition procedure created per Registration Set. All objects in ObjAccession table related to a given Registration Set are related to the Acquisition procedure.

This treatment has two sub-treatment categories:

`:singleset`:: If there is one Registration Set associated with an Accession Lot, the resulting Acquisition procedure's reference number is the :lotnumber value from the AccessionLot table.

`:multiset`:: If there are multiple Registration Sets per Accession Lot, the resulting Acquisition procedure's reference number begins with the :lotnumber value from the AccessionLot table. Some additional value must be added to ensure reference number uniqueness. If present, the AccessionLot.lotpattern field value will be used as a pattern to derive this. Otherwise a sequential digit segment may be added.

=== `:linkedlot`

NOTE: It is unknown if this ever occurs. I have not seen it in actual client data. This case would be that objects in ObjAccession are linked to an AccessionLot table record, but no entries in RegistrationSets table are linked to the objects

=== `:lotnumber`

NOTE: TMS allows population of the `acquisitionlot` field in the ObjAccession table _without_ linking that object to an entry in the AccessionLot table. This is the situation covered by this treatment.

One CS Acquisition procedure created per unique Acquisition Lot number value in ObjAccession table. All objects in ObjAccession table with the given :lotnumber value are related to the Acquisition procedure.

The resulting Acquisition procedure's reference number is the :lotnumber value from the AccessionLot table.

NOTE: Any `acquisitionnumber` values in rows with this treatment are collected, deduplicated, and written to a note field in the acquisition procedure, where they will be indexed for keyword search or an advanced search on that note field.

=== `:acqnumber`

This treatment applies to rows where `registrationsetid`, `acquisitionlotid`, and `acquisitionlot` fields are empty and the `acquisitionnumber` field is populated.

We have worked with client data where the same `acquisitionnumber` has been applied to many rows in the ObjAccession table, but different information has been entered for each object. A simplified example is shown below:

....
| acquisitionnumber | objectnumber | acquisitionsource | acquisitionmethod |
|               123 |        123.1 | Someone           | gift              |
|               123 |        123.2 | Someone else      | purchase          |
|               123 |        123.3 | Someone           | gift              |
|               123 |        123.4 | Someone else      | purchase          |
....

Therefore, this treatment does the following:

* Groups/clumps the records for each `acquisitionnumber` on unique data in all non-id fields in the record
* Creates one Acquisition procedure per group. Adds an incrementing numeral value to the `acquisitionnumber` value to create unique `acquisitionreferencenumber` values in CS.

With the above data, we would get two Acquisitions procedures, numbered 123.1 and 123.2.

Objects 123.1 and 123.3 would be related to Acquisition 123.1.

Objects 123.2 and 123.4 would be related to Acquisition 123.2.

=== `:onetoone`

This treatment applies to rows where `registrationsetid`, `acquisitionlotid`, `acquisitionlot`, and `acquisitionnumber` fields are empty.

One CS Acquisition procedure is created per ObjAccession row. The relevant object is related to the Acquisition procedure.

The resulting Acquisition procedure's reference number is the related object's object number.

== Dates in TMS ObjAccessions vs CS Acquisition

As you can see from the table below, there are only two TMS ObjAccessions date fields that have a clear one-to-one mapping to the CS acquisition procedure.

How to handle the other date values, if they appear in a client's data, is controlled by the <<mapping-options,mapping options>> described below.

NOTE: Some "No longer in use" TMS fields are included because we so sometimes find client data in these fields.

[cols="1,2,1,2", options="header"]
|===
|TMS field
|TMS data dictionary def
|CS field
|https://collectionspace.atlassian.net/wiki/spaces/COL/pages/506953729/Configuration+and+Data+Maps+-+Cataloging+Procedures+and+Vocabularies[CS schema] def

|accessionisodate
|Date of Accessioning (ISO date format)
|accessiondate
|The date on which an object formally enters the collection and is recorded in the accessions register.

|accessionminutes1
|No longer in use.  Replaced by ApprovalISODate1
|
|

|accessionminutes2
|No longer in use.  Replaced by ApprovalISODate2
|
|

|
|
|acquisitiondate
|The date on which title to an object or group of objects is transferred to the organization.

|approvalisodate1
|Approval Date 1 (ISO date format)
|
|

|approvalisodate2
|Approval Date 2 (ISO date format)
|
|

|authdate
|Date that an acquisition was authorized
|acquisitionauthorizerdate
|The date of which the Acquisition authorizer gives final approval for an acquisition to proceed.

|deedofgiftreceivediso
|Date Deed of Gift was received
|
|

|deedofgiftsentiso
|Date Deed of Gift was sent
|
|

|initdate
|Date that an acquisition was first initiated
|
|

|suggestedvalueisodate
|Value Date for the Suggested Accession Value in the linked Accession Lot
|
|
|===


== Mapping options

[NOTE]
====
The RegistrationSets and AccessionLot tables contain fields that appear in ObjAccession. The field handling specified for such fields in ObjAccession cascades to RegistrationSets and AccessionLot.

That is, you cannot opt to have :accessionvalue information treated differently for rows being processed as Registration Sets vs. one-to-one acquisition/object relations.
====

=== :accessionvalue_treatment

Applies to values in ObjAccession.accessionvalue or AccessionLot.accessionvalue

NOTE: recording values in ObjAccession.accessionvalue is apparently no longer supported in newer versions of TMS, replaced by linking to an ObjectValue record. However, we still see it in client data.

Default option:: `:valuation_control`

Other options to be developed on client request.

==== :valuation_control
Preprocessing for ObjAccession table/:onetoone treatment rows:

* First we merge in the values of any linked ObjectValue records
* If the value of :accessionvalue field = the value in the linked ObjectValue record, we delete it from ObjAccession (because we are going to create the relevant Valuation Control (VC) procedure from the ObjectValue record)
* If the value of :accessionvalue field is different from the value in the linked ObjectValue record, or if there is no linked ObjectValue record, the value is retained for further processing.

No preprocessing for AccessionLot.accessionvalue/:linkedlot treatment rows.

One CS Valuation Control (VC) procedure is created to reflect the recorded value. The VC procedure is linked to the relevant CS acquisition procedure and objects.

.Related options
* `:accessionvalue_type` - :valuetype to enter in VC procedures derived from this data. Default: "Original Value"

=== :approval_date_treatment
Applies to `:approvalisodate1` and `:approvalisodate2` fields in ObjAccession table.

The TMS `:authdate` field is mapped to CS `:acquisitionauthorizerdate` field, but that is a single-valued field.

This option specifies what to do with approval date data.

Default option:: `:acquisitionnote` -- map into this note field

* `:acquisitionprovisos`-- map into this note field
* `:drop` - do not migrate this information

.Related options:
* `:approval_date_note_format` -- if treatment involves mapping the value(s) to a note, should it be one combined note or two separate note values. Default: `:combined`. Alternate value(s): `:separate`
* `:approval_date_combined_prefix` -- if treatment involves mapping the value to a note, and `:approval_date_note_format` is `:combined`, this is the string prepended to the value to clarify the meaning of the value. Default: "Approval date(s): "
* `:approval_date_1_prefix` -- if treatment involves mapping the value to a note, and `:approval_date_note_format` is `:separate`, this is the string prepended to the value to clarify the meaning of the value of `:approvalisodate1`. Default: "Initial approval date: "
* `:approval_date_2_prefix` -- if treatment involves mapping the value to a note, and `:approval_date_note_format` is `:separate`, this is the string prepended to the value to clarify the meaning of the value of `:approvalisodate2`. Default: "Subsequent approval date: "

Other options may be developed on client request, if feasible.

=== :authorizer_org_treatment
Applies to :authorizer field in ObjAccession table **if name in field has been categorized by client as an Organization name**

`:authorizer` field is mapped to CS `:acquisitionauthorizer` field if it is a Person name, but Organization names cannot be used in this field.

The option specifies what to do with this data.

Default option:: `:acquisitionnote` -- map into this note field

.Alternate options:
* `:acquisitionprovisos`-- map into this note field
* `:acquisitionreason` -- map into this note field
* `:drop` - do not migrate this information

.Related options:
* `:authorizer_org_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Authorized by (organization name): "

Other options may be developed on client request, if feasible.

=== :authorizer_note_treatment
Applies to :authorizer field in ObjAccession table **if name in field has been categorized by client as treated as a note**

The option specifies what to do with this data.

Default option:: `:acquisitionnote` -- map into this note field

.Alternate options:
* `:acquisitionprovisos`-- map into this note field
* `:acquisitionreason` -- map into this note field
* `:drop` - do not migrate this information

.Related options:
* `:authorizer_note_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Authorizer note: "

Other options may be developed on client request, if feasible.

=== :dog_dates_treatment
Applies to :deedofgiftsentiso and :deedofgiftreceivediso fields in ObjAccession and RegistrationSets tables.

CS does not have structured data fields to record this info. The option specifies which note field this data should be mapped into.

"Deed of gift sent: " will be prepended to any :deedofgiftsentiso field values.

"Deed of gift received: " will be prepended to any :deedofgiftreceivediso field values.

Default option:: `:acquisitionnote`

.Alternate options:
* `:acquisitionprovisos`
* `:drop` - do not migrate this information

Other options may be developed on client request, if feasible.

=== :initiation_treatment
Applies to the :initiator and :initdate fields in the ObjAccession table.

CS does not have structured data fields to record this info. The option specifies which note field this data should be mapped into.

https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/transforms/obj_accession/initiation_note.rb[`Tms::ObjAccession::InitiationNote` ] generates a string with the following pattern:

`{initiation_prefix} {initiator}, {initdate}`

That string is mapped into the field indicated by this option:

Default option:: `:acquisitionreason`

.Alternate options:
* `:acquisitionnote`
* `:acquisitionprovisos`
* `:drop` - do not migrate this information

.Related options
* `:initiation_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Initiated: "

Other options may be developed on client request, if feasible.

=== Mapping names into :acquisitionsource vs. :owner

[IMPORTANT]
.CS definitions of "owner" and "acquisitionsource" fields
====
The following are taken from the Acquisition:Common schema https://collectionspace.atlassian.net/wiki/spaces/COL/pages/506953729/Configuration+and+Data+Maps+-+Cataloging+Procedures+and+Vocabularies[available on the CS wiki].

owner:: Details of a People, Person or Organisation who owned an object before title was transferred to the organization
acquisitionsource:: The People, Person, or Organization from whom an object was obtained, if different from the owner. The Acquisition source may be an agent or other intermediary between the acquiring organization and the Owner. For archaeological archives, use Acquisition source to record the excavating body responsible for preparing and depositing the archive with the organization.

We use these definitions to guide our initial/suggested mappings when developing custom migrations, but clients are not required to follow these. We can customize the role mappings into these fields to make them work for the client.
====

TMS Constituent names are merged into other TMS tables via the `ConRefs` and `ConRefDetails` tables, which indicate the following for each name to be merged in:

* constituent ID
* target table
* target record id (in target table)
* role id (looks up role values like "Donor" or "Vendor")
* role type id (looks up role type values like "Object Related" or "Acquisition Related")

The https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/role_types.rb[migration application's RoleTypes configuration] maps all TMS role types to the TMS tables into which Constituent names should be merged. These mappings can be overridden per client on request, but by default names tagged with "Acquisiton Related" role type will be merged into TMS ObjAccessions table, which then gets transformed/mapped into CS Acquisition procedures.

Each client will have used different role values on their Acquisition Related constituent references, so a per-client configuration mapping each role value to the appropriate CS field is set up.

.Example per-client constituent role treatment mapping for ObjAccession
[source,ruby]
----
  Kiba::Tms::ObjAccession.config.con_role_treatment_mappings = {
    :owner => ["Associated Source", "Attributed Source", "Donor", "Lender",
               "Source"],
    :acquisitionsource => ["Vendor"]
  }
----

We do an initial mapping based on the definitions in the info box above, but these can be changed on client request.

[NOTE]
====
Due to differences in data model granularity between TMS (more granular in this case) and CS, the role values for names mapped to `:owner` and `:acquisitionsource` are, by default, lost in migration.

If you view the Acquisition procedure form in your CS instance, you will see there is no structured place to put this information.

If it is crucial for you to retain the TMS role information in the CS Acquisition procedure, we can develop a mapping of owner/acquisitionsource name + role value into one of the notes fields. Thus far, no TMS client has requested this
====

=== :percentowned_treatment

Applies to ObjAccession.currpercentownership and RegistrationSets.percentowned fields.

CS does not have structured data fields to reflect this information. The option specifies which note field this data should be mapped into.

Default option:: `:acquisitionprovisos`

.Alternate options:
* `:acquisitionnote`
* `:drop` - do not migrate this information

.Related options
* `:percentowned_prefix` -- if treatment involves mapping the value to a note, this is the string prepended to the value to clarify the meaning of the value. Default: "Percent owned: "

Other options may be developed on client request, if feasible.
