:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

=  Mapping options for Objects


toc::[]

== Mapping options for tables merged into Objects

=== ObjectNames

==== :migrate_inactive

Whether to migrate ObjectNames rows where `active` = 0

Default:: true

.Alternative options
* false

=== ObjectNameTypes

==== :mappings

Controls how values from ObjectNameTypes table _that are used in migrating data_ will map to CS nameTypes static option list.

Values not used in migrating data are not added to CS.

Default:: none, as this is very client-specific.

=== `TextEntries` merge treatments

The TMS `TextEntries` table stores text values of different types for merge into various target tables, including `Objects`.

Your Migration Specialist will let you know about any custom cleanup and preparation of these values prior to merging them into `Objects`. Usually this involves some handling of any `:purpose` and `:remarks` values that may have been recorded for individual text entries. Typically we combine these values into the `:textentry` field so that we have one main content field to merge.

Constituent names associated with text entries will have been merged in as `:org_author` and `:person_author` fields prior to merge into `Objects`.

Each `:texttype` must be assigned a treatment, which is used to merge the text entry into the `Objects` data as shaped for CollectionSpace. The available treatments are:

==== `drop`

Text entries with this treatment assigned to their `:texttype` will be omitted from the migration.

==== `color`

Prepend "Color note: ". Map to `physicalDescription`.

==== `note_comment`

Mapped to intermediate field that will be combined with
