# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  # Standard's config uses custom cops,
  # so it must be loaded
  - standard
  # Loaded after standard so that standard's required version is used and we do not get version conflicts
  - rubocop-performance

inherit_gem:
  standard: config/ruby-3.1.yml
  standard-performance: config/base.yml

inherit_from:
  - https://raw.githubusercontent.com/kspurgin/code-quality/main/configurations/rubocop/standard-override.yml

# Per project, you can enable cops (which are disabled in Standard by default)
#   here
#
# Metrics:
#   Enabled: true

# Global options, like Ruby version
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
