:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

= Acquisitions data preparation details

This page details how the data in the TMS table is processed to produce CollectionSpace Acquisition procedures, as well as relationships between acquisitions and objects.

toc::[]

== Overview of possible approaches required

Depending on client data entry practices/what tables they have used in TMS, we need up to three different approaches:

* If accession lots have been used (i.e. there are AcquisitionLotID values in the ObjAccessions table), we need to use the `Lot/Set` approach to create some Acquisition procedures
* If AcquisitionLot values have been assigned in the ObjAccessions table, but rows with those values do not have AcquisitionLotID values, we need to use the `LotNumber` approach to create some Acquisition procedures
* 

=== `OneToOne` approach

Used for rows in ObjAccessions table without AcquisitionLotID or AcquisitionLot values.

Creates one Acquisition procedure per row.

The Acquisition procedure derived from the row is related to the Object represented by that row.

=== `LotNumber` approach

Used if there are ObjAccessions rows having `AcqisitionLot` values, but lacking `AcquisitionLotID` values.

One Acquisition procedure is created per unique `AcquisitionLot` value.

That Acquisition procedure is related to all Objects represented by rows with the source `AcquisitionLot` value.

NOTE: This assumes that all details in rows with the same `AcquisitionLot` value will have all the same data values in all other columns that get mapped to Acquisitions. We need to develop a report to verify this is the case.

=== `LinkedLot` approach

Used if there are `AcquisitionLotID` values in the ObjAccessions table. There will also be populated entries in the AccessionLots and RegistrationSets tables.

One or more registration sets can be associated with a given accession lot. The registration set level is where most of the Acquisition procedure source data fields are populated, so we create one Acquisition procedure per registration set.

Each Acquisition procedure derived from a registration set is linked to the Objects that list that RegistrationSetID in the ObjAccessions table.

[CAUTION]
====
CS does not support hierarchical Acquisitions, so if a client has any acquisition lots that have multiple registration sets per lot, some structural data is lost.

We need to assign a unique reference number per Acquisition procedure. For lots having multiple sets, we will need to derive those from the `LotNumber` value assigned in the AccessionLots table, by adding a segment to the end.

This means it will be possible to search for all Acquisitions whose reference numbers start with a given lot number, but we will not have an Acquisition procedure that is linked to all objects in all registration sets for a given lot.
====

[NOTE]
====
Currently no TMS migration we have handled has involved multiple registration sets per accession lot, so the existing codebase does not handle creation of multiple Acquisition procedures per accession lot due to multiple sets in the lot. We can add that functionality should we work on a migration that needs it.
====
