:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: https://raw.githubusercontent.com/lyrasis/kiba-tms/main/doc/img
endif::[]

= Constituents data processing details

This page details how the data in the TMS Constituents table is processed in the overall xref:name_compilation.adoc[Name compilation] process. 

toc::[]

== Preferred name field

Prior to processing constituent data, we ask the client to https://github.com/lyrasis/collectionspace-migration-explainers/blob/main/docs/choosing_preferred_name_form_for_persons.adoc[identify their preferred name form for persons].

If they choose direct form, the preferred name field from the Constituents and ConAltNames tables is `displayname`.

If they choose inverted form, it is `alphasort`

In the remainder of this document, "preferred name" refers to the value of the preferred name field. 

== Processing steps

=== Remove non-migrating and empty fields, test row

Non-migrating fields will be marked as such in your data mapping details spreadsheet. The reason for omission from migration is given there.

In a number of tables, TMS appears to create a row with the id "-1" with no data. This row is present in Constituents table and is removed from migration.

`displaydate`, `begindateiso`, and `enddateiso` fields are deleted because they are handled in the xref:con_dates.adoc[ConDates table processing], the results of which are later merged back into the main Constituents data.


=== Determine CollectionSpace (CS) authority type

Next, we categorize each constituent name into Person or Organization.

For constituent names with a constituenttype coded in TMS, we use https://github.com/lyrasis/kiba-tms/blob/main/lib/kiba/tms/constituents.rb[the mapping configured for Constituents] (search for `setting :type_mapping` in the linked page).

For constituent names without a constituenttype coded in TMS, we attempt to xref:deriving_authority_category_from_name_data.adoc[derive the appropriate category].

The processing keeps separate categories mapped from explicit TMS constituenttype (Person, Organization), and derived guesses (Person?, Organization?). For ease of further processing, a normalized authority type is also created for each name (person, organization).

=== Remove redundant non-preferred names

Matching is case insensitive.

....
| displayname    | alphasort      |
|----------------+----------------|
| Doe Associates | Doe associates |
....

becomes:

....
| displayname    | alphasort |
|----------------+-----------|
| Doe Associates |           |
....

=== Organization name cleanup/warnings

NOTE: The examples in this section assume the preferred name field is `displayname`

The following processing is applied to rows where normalized authority type = Organization:

==== Remove `institution` value if it is the same as the preferred name

Matching is case insensitive.

....
| displayname      | institution      |
|------------------+------------------|
| ACME Corporation | Acme Corporation |
....

becomes:

....
| displayname      | institution |
|------------------+-------------|
| ACME Corporation |             |
....

==== Remove `institution` value if it is the same as the non-preferred form of name

Matching is case insensitive:

....
| displayname      | alphasort  | institution |
|------------------+------------+-------------|
| ACME Corporation | ACME Corp. | Acme Corp.  |
....

becomes:

....
| displayname      | alphasort  | institution |
|------------------+------------+-------------|
| ACME Corporation | ACME Corp. |             |
....

==== Conditionally remove name details

Name details are values in fields for breaking up personal names: `nametitle`, `salutation`, `firstname`, `middlename`, `lastname`, `suffix`.

If a row matches the conditions explained below, all of the name details fields are cleared.

The core name details fields used to determine whether a row matches the conditions are: `firstname`, `middlename`, `lastname`, `suffix`.

.Original data
....
| displayname      | position | lastname       | firstname    |
|------------------+----------+----------------+--------------|
| Doe & Associates |          | Doe Associates |              |
| Moe Press, Inc.  |          | Moe Press      | Inc          |
| Poe Press, Inc.  |          | Poe Press      | Incorporated |
| Jane Doe Art     |          | Doe            | Jane         |
| Jane Smith Art   | owner    | Smith          | Jane         |
....

.Processed data
....
| displayname      | position | lastname       | firstname    |
|------------------+----------+----------------+--------------|
| Doe & Associates |          | Doe Associates |              |
| Moe Press, Inc.  |          |                |              |
| Poe Press, Inc.  |          | Poe Press      | Incorporated |
| Jane Doe Art     |          |                |              |
| Jane Smith Art   | owner    | Smith          | Jane         |
....

.Conditions for name detail removal
* There is no `position` value. If there is a position, we assume the name details indicate a person holding that position within the organization. These name details will later be extracted out to separate person names.
** The "Jane Smith Art" row does not have name details removed. 
* The values of all core name detail fields are substrings of the preferred name
** "Doe Associates" is retained as `lastname` because that string cannot be found in "Doe & Associates"
** "Poe Press" can be found in "Poe Press, Inc.", but "Incorporated" cannot, so no name details are removed

==== Add `check_org_names` column

Set its value to "y" if:

* there is an `institution` value remaining (i.e. some organization name not the same as the preferred or non-preferred name is recorded for the organization)
* non-preferred name of organization is different from the preferred name

=== Add `namedata` field

This field concatenates the values from the following fields: `displayname`, `alphasort`, `lastname`, `firstname`, `middlename`, `institution`

It is used to produce a separate report of Constituent table rows that will be dropped from the migration because they have no name information. Each CS authority requires a name value. 

=== Remove non-preferred form of name unless client opts to migrate these as variant names

The default is to not create variant names in CS from the non-preferred form of name.

Usually the non-preferred name is the exact same name as the preferred name, in a different order.

If the non-preferred form of name is not migrating, we don't need to look at it or deal with it in the cleanup steps.

=== Merge in date data

Details on how date data from the Constituents and ConDates tables are processed into a mergeable format are covered in xref:con_dates.adoc[ConDates table processing].

The `birth_foundation_date`, `death_dissolution_date`, and `datenote` fields are merged in from the results of that processing.

=== Append date values to names (optionally)

The default is to do this for normalized-duplicate names. In this case, we:

* produce normalized form of name
* combine normalized form of name with normalized authority type
* identify duplicates on that combined value
* append date values to the duplicate rows
* remove normalized, combined, and duplicate flag values

See xref:../mapping_options/constituents.adoc[Constituent mapping options] for other options.

=== Flag duplicate names

* produce normalized form of name
* combine normalized form of name with normalized authority type
* flag duplicates on that combined value

This flag is used to produce a separate duplicate name report.

=== Optional field values converted/mapped

By default these fields are omitted from migration, since the CS data model does not support any functionality based on them: `approved`, `active`, `isstaff`, `isprivate`.

If default migration settings are used, we delete these fields.

If a client specifies a need to migrate any of these fields, we handle them as specified in xref:../mapping_options/constituents.adoc[Constituent mapping options].

