# frozen_string_literal: true

module Kiba::Tms::AltNumsForObjTypeCleanup
  module_function

  extend Dry::Configurable

  # @return [String] used as the namespace for auto-generated registry
  #   entries and the base for output file names
  setting :cleanup_base_name,
    default: "alt_nums_for_obj_type_cleanup",
    reader: true

  # @return [Symbol] registry entry job key for the job whose output will be
  #   used as the base for generating the cleanup worksheet. Iterations of
  #   cleanup will be layered over this output in the auto-generated
  #   :cleanup_base_name__base_cleaned job
  setting :base_job,
    default: :alt_nums__types_for_objects,
    reader: true

  # @return [Array<Symbol>] tags assigned to all jobs generated by extending
  #  IterativeCleanupable
  setting :job_tags,
    default: %i[alt_nums objects cleanup],
    reader: true

  # @return [Array<Symbol>] nil/empty fields to be added to worksheet
  setting :worksheet_add_fields,
    default: %i[correct_type treatment note],
    reader: true

  # @return [Array<Symbol>] order of fields (in worksheet output)
  setting :worksheet_field_order,
    default: %i[number_type correct_type treatment note
      occurrences occs_with_remarks occs_with_begindate
      occs_with_enddate
      example_rec_nums example_values],
    reader: true

  # @return [Array<Symbol>] fields included in the fingerprint value
  setting :fingerprint_fields,
    default: %i[number_type correct_type treatment note],
    reader: true

  # @return [Symbol, Array<Symbol>, nil] field or fields included in
  #   the fingerprint value that should be ignored when flagging
  #   changes
  setting :fingerprint_flag_ignore_fields,
    default: %i[number_type correct_type treatment note],
    reader: true

  extend Tms::Mixins::IterativeCleanupable
end
