# frozen_string_literal: true

module Kiba::Tms::PlacesCleanupInitial
  extend Dry::Configurable

  module_function

  # @return [String] used as the namespace for auto-generated registry
  #   entries and the base for output file names
  setting :cleanup_base_name,
    default: "places_cleanup_initial",
    reader: true

  # @return [Symbol] registry entry job key for the job whose output will be
  #   used as the base for generating the cleanup worksheet. Iterations of
  #   cleanup will be layered over this output in the auto-generated
  #   :cleanup_base_name__base_cleaned job
  setting :base_job,
    default: :places__norm_unique,
    reader: true

  # @return [Array<Symbol>] tags assigned to all jobs generated by extending
  #  IterativeCleanupable
  setting :job_tags,
    default: %i[places cleanup],
    reader: true

  # @return [Array<Symbol>] nil/empty fields to be added to worksheet
  def worksheet_add_fields
    Tms::Places.worksheet_added_fields
  end

  # @return [Array<Symbol>] order of fields (in worksheet output)
  def worksheet_field_order
    base = []
    base << Tms::Places.hierarchy_fields.reverse
    base << (Tms::Places.source_fields - Tms::Places.hierarchy_fields)
    base << worksheet_add_fields
    base << %i[occurrences norm_combineds norm_fingerprints
      clean_fingerprint]
    base.flatten.uniq
  end

  # @return [Array<Symbol>] fields included in the fingerprint value
  def fingerprint_fields
    Tms::Places.source_fields
  end

  # @return [Symbol, Array<Symbol>, nil] field or fields included in
  #   the fingerprint value that should be ignored when flagging
  #   changes
  setting :fingerprint_flag_ignore_fields,
    default: nil,
    reader: true

  extend Tms::Mixins::IterativeCleanupable

  # String used to delimit/split multiple :norm_fingerprint values in cleanup
  #   process
  setting :norm_fingerprint_delim, default: "////", reader: true

  def base_job_cleaned_pre_xforms
    Kiba.job_segment do
      transform Rename::Field,
        from: :norm_fingerprint,
        to: :fingerprint
    end
  end

  def base_job_cleaned_post_xforms
    Kiba.job_segment do
      transform Rename::Field,
        from: :fingerprint,
        to: :norm_fingerprint
    end
  end
end
