:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= ConDates (constituent dates) data cleanup worksheet for TMS-to-CS migration

toc::[]

[IMPORTANT]
====
The spreadsheet you have been given is for your review only.

You may use it to clean up existing data in TMS prior to providing data for the production migration phase. Or you can use the version of this report provided during the production migration to inform cleanup in CollectionSpace after migration as desired.

*It is _not_ a worksheet in which you can make changes that will be merged back into the migration.*
====

== Dates in CS Person/Organization records

TIP: We recommend you familiarize yourself with the Person and Organization records in your CS staging/training instance. Go to `Create New` and choose `Local` under Person and/or Organization.

The options for recording _structured_ date data in these records are presently fairly simple:

=== Person

* one birth date
* one death date

Other date information can be massaged into a textual note and mapped into the Biographical note

=== Organization

* one foundation date
* one dissolution date

In TMS constituents mapped to organization records, "birth" dates will be mapped to foundation date, and "death" dates will be mapped to dissolution date.

Other date information can be massaged into a textual note and mapped to the History note

== How this data was prepared

=== Constituents table
* strings matching `nationality` field are removed from `displaydate` field
* best reasonable programmatic attempt made to convert `displaydate` values into parseable dates and determine date type intended
* compare the values derived from `displaydate` with `begindateiso` and `enddateiso` values. If the same, `displaydate` value is dropped. If one contains the other (ie. "1975" and "Jun 20 1975", then the fuller date is kept in the appropriate `*dateiso` field. If different (other than a fuller date), a `datenote` value is created from `displaydate` value

=== ConDates table (not used by all TMS clients)
* Structured start and end dates entered in TMS are converted to a single date value. If the start/end dates differ, this results in a single _date range_ value
* Variant forms of `datedescription` (i.e. "birth", "birthday", "birth year", "began", etc.) are reconciled into one consistent value ("birth") to inform how to map date data into CS persons and organization.

=== Combined data
* Data from Constituents and ConDates tables are combined into one table
* Identical date values for the same constituent appearing in both tables are removed
* Less-full date values that partially match (are contained in) values for the same constituent are removed
* `datenote` value is derived for data that does not map into available structured CollectionSpace person/organization date fields. These include:
** dates other than birth/death dates (person) or foundation/dissolution dates (organization)
** date remarks
** subsequent, different birth/death date values recorded for the same constituent
* Data review/quality warnings are generated
* Date parser is run on the date values that will be mapped to birth/foundation and death/dissolution date fields in CS, in order to identify unrecognized date formats and other issues

== Structure of report spreadsheet

The following columns reflect how the data is structured in TMS' database tables: `constituentname`, `constituentid`, `date`, `remarks`.

The following columns indicate how each row will map into the relevant CS Person or Organization authority, given the current TMS data: `birth_foundation_date`, `death_dissolution_date`, `datenote`.

The following columns indicate how the date will be interpreted into structured date data in CS (see Person > Birth date field and click into it as an example): `parsed_date_start`, `parsed_date_end`.

The following columns are informational for the review/cleanup process: `warn`, `date_parser_warnings`



== Categories of things to look at in review/cleanup

=== rows with warnings

Limit to rows with `warn` column not empty. The meanings of the warnings are explained below:


==== no date type in datedescription

No date type information is available to indicate how we should map date data.

If not fixed, will be migrated as a date note as shown in `datenote` field.

==== unknown/unmapped date type in datedescription

Date type information could not be programmatically mapped to a standard date type for mapping. Basic standard date types are: birth, death, active.

If not fixed, will be migrated as a date note as shown in `datenote` field.

==== no date value

This often indicates possible malformed or mis-entered data.

If not fixed, any data present will be migrated as a date note as shown in `datenote` field.

==== date value is range

Range is expected for "active" dates, so this warning should not appear on those. Otherwise, the fact that a range was entered may indicate both birth and death were entered under birth date.

If not fixed, date will be migrated as the date range.

==== multiple values for birth or death date for constituent id

More than one birth date and/or death date entry exists for a single constituent. CS takes only a single value for each of these date fields.

If the multiple values are in the data provided for the production migration, the first value (when sorted by `condateid`) will migrate into the relevant date field in CS Person/Org record. The subsequent values will be migrated as notes.

==== unparseable date value

The date value mapped to `birth_foundation_date` or `death_dissolution_date` cannot be parsed into a valid date for ingest into CS.

"unparseable date value" is followed by more detailed information your Migration Specialist can use to determine why a date isn't parseable.

The most common reason (indicated by additional "Emendate untokenizable") is that extra information (not part of an actual date value) has been included in the date value. For these we recommend that the extra information be moved to remarks field if it needs to be retained. 

=== rows with `datedescription` = birth or death, AND a `datenote` value

These indicate that redundant information may have been recorded, or that place or other information that does not belong in ConDates may have been recorded here.

=== rows with `date_parser_warnings` values

These warnings are from the date processing tool, and indicate that a date was successfully parsed, but a particular https://github.com/kspurgin/emendate/blob/main/docs/options.adoc[date parsing option] was applied, interpreting the date in a certain way. You will want to review that the dates are being parsed as expected, and let your Migration Specialist know if a different date interpretation option should be used.

Note that date parser options apply across the board to all date value being parsed. (Example: It is not possible to sometimes interpret "03/04/2001" as March 4 and sometimes as April 3.) If your dates have inconsistent formatting, we will want to use the option/interpretation that is correct for the majority of the values. The other values will need to be manually cleaned up. 
