:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Name compilation worksheet data preparation

This document explains how your TMS Constituents (and other name data) has been programmatically prepared for migration into CollectionSpace (CS), and options you have for changing how this has been handled.

NOTE: This documentation covers TMS migrations in general, so may discuss data patterns not present in your data.

IMPORTANT: Your Contituent (and other) names will migrate into Person and Organization authorities in CS. The conceptual/data model for Constituents in TMS is very different from (and more complex than) the conceptual/data model for Person and Organization authorities. *We strongly recommend you log into your staging instance site and familiarize yourself with Person and Organization records*.

toc::[]


