# frozen_string_literal: true

module Kiba
  module Tms
    module Table
      class List
        class << self
          def call
            %w[
               AccessionLot
               AccessionMethods
               AltNums
               ClassificationNotations
               ClassificationXRefs
               Classifications
               ConAddress
               ConAltNames
               ConDates
               ConEMail
               ConPhones
               ConTypes
               ConXrefDetails
               ConXrefs
               CondLineItems
               Conditions
               Constituents
               Countries
               Currencies
               Departments
               DimItemElemXrefs
               DimensionElements
               DimensionTypes
               DimensionUnits
               Dimensions
               DispositionMethods
               EMailTypes
               EnvironmentalReqExt
               EnvironmentalReqTypes
               ExhLoanXrefs
               ExhObjLoanObjXrefs
               ExhObjXrefs
               ExhVenObjXrefs
               ExhVenuesXrefs
               ExhibitionTitles
               Exhibitions
               FlagLabels
               IndemnityResponsibilities
               InsuranceResponsibilities
               LoanObjStatuses
               LoanObjXrefs
               LoanPurposes
               LoanStatuses
               Loans
               LocApprovers
               Locations
               LocHandlers
               LocPurposes
               MediaFiles
               MediaMaster
               MediaRenditions
               MediaTypes
               MediaXrefs
               ObjAccession
               ObjCompStatuses
               ObjCompTypes
               ObjComponents
               ObjContext
               ObjDeaccession
               ObjInsIndemResp
               ObjInsurance
               ObjLocations
               ObjectStatuses
               Objects
               OverallConditions
               PhoneTypes
               Relationships
               RegistrationSets
               RoleTypes
               Roles
               StatusFlags
               SurveyTypes
               TermMasterGeo
               TermMasterThes
               TermTypes
               Terms
               TextEntries
               TextTypes
               ThesXrefTypes
               ThesXrefs
               ThesaurusBases
               TitleTypes
               AddressTypes
               Associations
               AssocParents
               ConDisplayBios
               ConGeoCodes
               ConGeography
               ConveyanceTypes
               ConXrefSets
               CrateProjects
               Crates
               CrateTypes
               DimensionMethods
               GeoCodes
               ObjDates
               ObjectLevels
               ObjectNames
               ObjectNameTypes
               ObjectTypes
               ObjGeography
               ObjIncoming
               ObjIncPurposes
               ObjRights
               ObjRightsTypes
               ObjTitles
               ReferenceMaster
               RefFormats
               RefXRefs
               ShippingMethods
               StorageFormats
               StorageMethods
               TextStatuses
               TreatmentPriorities
               ValuationPurposes
              ].map{ |table| "#{table}.csv" }
          end
        end
      end
    end
  end
end
