# frozen_string_literal: true

module Kiba
  module Tms
    module Table
      class List
        class << self
          def call
            %w[
               AccessionLot.csv
               AccessionMethods.csv
               AltNums.csv
               ClassificationNotations.csv
               ClassificationXRefs.csv
               Classifications.csv
               ConAddress.csv
               ConAltNames.csv
               ConDates.csv
               ConEMail.csv
               ConPhones.csv
               ConTypes.csv
               ConXrefDetails.csv
               ConXrefs.csv
               CondLineItems.csv
               Conditions.csv
               Constituents.csv
               Countries.csv
               Currencies.csv
               Departments.csv
               DimItemElemXrefs.csv
               DimensionElements.csv
               DimensionTypes.csv
               DimensionUnits.csv
               Dimensions.csv
               DispositionMethods.csv
               EMailTypes.csv
               EnvironmentalReqExt.csv
               EnvironmentalReqTypes.csv
               ExhLoanXrefs.csv
               ExhObjLoanObjXrefs.csv
               ExhObjXrefs.csv
               ExhVenObjXrefs.csv
               ExhVenuesXrefs.csv
               ExhibitionTitles.csv
               Exhibitions.csv
               FlagLabels.csv
               IndemnityResponsibilities.csv
               InsuranceResponsibilities.csv
               LoanObjStatuses.csv
               LoanObjXrefs.csv
               LoanPurposes.csv
               LoanStatuses.csv
               Loans.csv
               Locations.csv
               LocPurposes.csv
               MediaFiles.csv
               MediaMaster.csv
               MediaRenditions.csv
               MediaTypes.csv
               MediaXrefs.csv
               ObjAccession.csv
               ObjCompStatuses.csv
               ObjCompTypes.csv
               ObjComponents.csv
               ObjContext.csv
               ObjDeaccession.csv
               ObjInsIndemResp.csv
               ObjInsurance.csv
               ObjLocations.csv
               ObjectStatuses.csv
               Objects.csv
               OverallConditions.csv
               PhoneTypes.csv
               Relationships.csv
               RegistrationSets.csv
               RoleTypes.csv
               Roles.csv
               StatusFlags.csv
               SurveyTypes.csv
               TermMasterGeo.csv
               TermMasterThes.csv
               TermTypes.csv
               Terms.csv
               TextEntries.csv
               TextTypes.csv
               ThesXrefTypes.csv
               ThesXrefs.csv
               ThesaurusBases.csv
               TitleTypes.csv
               AddressTypes.csv
               Associations.csv
               AssocParents.csv
               ConDisplayBios.csv
               ConGeoCodes.csv
               ConGeography.csv
               ConveyanceTypes.csv
               ConXrefSets.csv
               CrateProjects.csv
               Crates.csv
               CrateTypes.csv
               DimensionMethods.csv
               GeoCodes.csv
               ObjDates.csv
               ObjectLevels.csv
               ObjectNames.csv
               ObjectNameTypes.csv
               ObjectTypes.csv
               ObjGeography.csv
               ObjIncoming.csv
               ObjIncPurposes.csv
               ObjRights.csv
               ObjRightsTypes.csv
               ObjTitles.csv
               ReferenceMaster.csv
               RefFormats.csv
               RefXRefs.csv
               StorageFormats.csv
               StorageMethods.csv
               TextStatuses.csv
               TreatmentPriorities.csv
               ValuationPurposes.csv
              ]
          end
        end
      end
    end
  end
end
